Downgrade pydantic to <2.0
2.0 cannot be used with pyoxidizer, probably because of the Rust module
The error message:
error[PYOXIDIZER_PYTHON_EXECUTABLE]: adding PythonExtensionModule<name=pydantic_core._pydantic_core>

    Caused by:
        extension module pydantic_core._pydantic_core cannot be loaded from memory but memory loading required
       --> ./pyoxidizer.bzl:237:5
        |
    237 |     exe.add_python_resources(exe.pip_install(["--no-deps", "-r", "requirements.txt"]))
        |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ add_python_resources()

error: adding PythonExtensionModule<name=pydantic_core._pydantic_core>